# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: 'curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar'
  displayName: 'Download the latest Unified Agent'

- script: 'java -jar wss-unified-agent.jar -apiKey ad4d5a5ffdbe426d8ea8852afcee80b1188c903071fc470385b946d5446a6ce6 -project UAintegrationAzure1'
  displayName: 'Run Unified Agent Scan'